#!/usr/bin/env bash

enter "${release_path}"

if file_is_nonempty *.gems &&
  command_exists "rvm"
then
  rvm gemset import *.gems
fi

if file_is_nonempty "Gemfile"
then
  if ! command_exists bundle
  then
    install_gems bundler
  fi
elif file_contains "config/environment.rb" "config.gem"
then
  rake gems:install
else
  log "No Gemfile or config.gem entries detected, skipping gems."
fi

if ! command_exists rake
then
  install_gems rake 0.8.7
fi

if command_exists rake
then
  rake db:create
  rake db:migrate
else
  warn "'rake' command is missing, "\
    "skipping db:create and db:migrate tasks."
fi

