#!/usr/bin/env bash

dependencies=( pcre )

modules package service

package_definition \
  base_url "http://haproxy.1wt.eu/download/${package_version%.*}/src/" \
  docs_url "http://haproxy.1wt.eu/download/${package_version%.*}/doc/configuration.txt"

