#!/usr/bin/env bash

dependencies=( pcre )

modules package service

package_definition \
  base_url "http://haproxy.1wt.eu/download/${package_version%.*}/src/" \
  docs_url "http://haproxy.1wt.eu/download/${package_version%.*}/doc/configuration.txt"

service_flags+=( -f "/etc/haproxy/haproxy.conf" )
service_start_flags+=( )
service_restart_flags+=( )
service_stop_flags+=( )


