#!/usr/bin/env bash

modules rvm

[[ -n "$environment" ]] || fail "'environment' is not set (bdsmrc)"
[[ -n "$RAILS_ENV" ]] || fail "'RAILS_ENV' is not set (bdsmrc)"
[[ -n "$project" ]] || fail "'project' is not set (bdsmrc)"

pidfile="$current_path/pids/$project.rainbows.pid"
[[ -s "$pidfile" ]] && pidfile_pid="$(cat "$pidfile")"

if [[ -n "$pidfile_pid" ]] && [[ -d "/proc/${pidfile_pid}" ]] ; then

  master_pid="$pidfile_pid" # Running and matches pidfile.

elif [[ -n "$running_pid" ]] && [[ -d "/proc/${running_pid}" ]] ; then
  if [[ -n "$project" ]] ; then
    running_pid="$(ps auxww | grep '[r]ainbows' | grep 'master' | awk '/'${project}'/{print $2}')"
  else
    $bdsm_scripts_path/log "warn" "'project' should be set in ~/.bdsmrc"
    running_pid="$(ps auxww | grep '[r]ainbows' | grep 'master' | awk '{print $2}')"
  fi
  printf "$running_pid" > "$pidfile" # Make sure the correct running pid is in the pidfile.
  master_pid="$running_pid" # Set to the found running pidfile.
else
  unset master_pid # Not found!
fi

[[ -d $current_path ]] && builtin cd $current_path

[[ -s "$current_path/.rvmrc" ]] && source "$current_path/.rvmrc"

