#!/usr/bin/env bash

androidsdk_configure()
{
  true # no-op
}

androidsdk_build()
{
  true # no-op
}

androidsdk_install()
{
  copy_paths to "${install_path}" add-ons platforms tools
  copy_files to "${install_path}" "SDK Readme.txt"
  link from "${install_path}/tools" to "${install_path}/bin"
}

