#!/usr/bin/env bash

description "Extension for managing redis (http://wiki.redis.org/Main)."

action "install" "Installs ${package_name} ${package_version}."
action "setup" "Setup redis configuration."
action "start" "Startup redis."
action "stop" "Stop redis."
action "restart" "Restart redis."
action "info" "Display redis server INFO"
action "help" "Display this help text."

show_help usage

