#!/usr/bin/env bash

description "Extension for managing ${extension} (${website_url})."

action "service [action]" "Control ${extension} service."
action "server [action]" "Work with ${extension} server configurations."
action "package [action]" "Use ${extension} package."
action "[namespace] help" "Display help for namespaces ${extension} {service,server,package,conf}."

show_help usage

