#!/usr/bin/env bash

action "package install" "Installs ${package_name} ${package_version}."
action "package uninstall" "Installs ${package_name} ${package_version}."

action "start" "Start passenger."
action "stop" "Stop  passenger."
action "restart" "Restart passenger."
action "help" "Display this help text."

