#!/usr/bin/env bash

description "${extension} BDSM extension."

action "package install" "Installs getopt package."
action "package uninstall" "Uninstalls getopt package."
action "help" "Display help for ${extension}."

show_help usage
