#!/usr/bin/env bash

modules std/package

package_definition \
  url "${package_base_url}/${package_version}/p7zip_${package_version}_src_all.${archive_format}" \
  file "p7zip_${package_version}_src_all.${archive_format}" \
  dir "${package_name}_${package_version}"

