#!/usr/bin/env bash

true \
  "${discard_path:="${shared_path}/discard"}" \
  "${previous_path:=${project_path}/previous}" \
  "${stage_path:=${project_path}/stage}"

ensure_paths_exist \
  "$previous_path" \
  "$discard_path"

previous_releases=$(
  find "${previous_path}/" -mindepth 1 -maxdepth 1 -type d | sort
)

previous="${previous_releases[0]}"

old_releases=($(
  find "${previous_path}/" -mindepth 1 -maxdepth 1 -type d | sort -r |
  awk "NR > ${keep_releases:-3} { print \$0 }"
))

timestamp="$(date +%m.%d.%YT%H:%M:%S)"

deploy_steps=(
  update_repository stage_current configure symlink
  replace_current cleanup record
)

if [[ -z "${repository_url}" ]]
then
  error "The project's repository_url must be set in configuration files (eg: ~/.bdsmrc)"
fi
