#!/usr/bin/env bash

action "package install" "Installs ${package_name} ${package_version}."
action "package uninstall" "Installs ${package_name} ${package_version}."

action "service [action]" "Control ${extension} service."

action "backup [action]" "configurations."
action "conf [action]" "Work with ${extension} server configuration file."
action "[namespace] help" "Display help for namespaces ${extension} {service,package,conf,backup}."

show_help usage

