#!/usr/bin/env bash

action "service [action]" "Control ${extension} service."
action "package [action]" "Use ${extension} package."
action "backup [action]" "configurations."
action "conf [action]" "Work with ${extension} server configuration file."
action "[namespace] help" "Display help for namespaces ${extension} {service,package,conf,backup}."

show_help usage

