#!/usr/bin/env bash

remove_paths \
  "${prefix_path}/${package_name}" \
  "${prefix_path}/${package_name}-${package_version}"

remove_files \
  /etc/profile.d/postgresql.sh \
  /etc/ld.so.conf.d/postgresql.conf \
  "${init_scripts_path}/postgresql"

user_delete "${package_user}"

log "Removal of ${package_name} complete."
