#!/usr/bin/env bash

#  First do an install
extension_action "postgresql" "install"

# Then do the upgrade parts
# TODO: Upgrade code
# move and symlink to preserve the old postgresql.conf, pg_hba.conf files
# pg_upgrade / move databases from old system.

