#!/usr/bin/env bash

mongodb_install()
{
  ensure_paths_exist
  files=$(find "bin/" -type f)
  copy_files_to "${install_path}" "${files[@]}"
}

mongodb_configure()
{
  path_exists "${install_base_path}" || activate_package
}
