#!/usr/bin/env bash

mongodb_install()
{
  ensure_paths_exist "${install_path}"
  files=$(find "${source_path}/${package_dir}/bin/" -type f)
  copy_files_to "${install_path}" "${files[@]}"
}

mongodb_configure()
{
  path_exists "${install_base_path}" || activate_package
}
