#!/usr/bin/env bash

nginx_list()
{
  local master_list=("$(ps auxww | head -1)") worker_list=()

  if (( master_pid > 0 ))
  then
    while read -r line
    do
      if [[ "$line" =~ nginx ]]
      then
        if [[ "$line" =~ master ]]
        then
          master_list+=("${line}")
        elif [[ "$line" =~ worker ]]
        then
          worker_list+=("${line}")
        fi
      fi
    done < <(ps auxww | awk '/[n]ginx/')

    array_join master_list "\n"
    echo
    array_join worker_list "\n"
    echo
  else
    log "No Nginx master processes was found."
  fi
}

