#!/usr/bin/env bash

shocco_download()
{
  local shocco_src_path="${src_path}/$(scm_identifier "${package_base_url}")/"
  scm_get ${package_base_url} ${shocco_src_path}
}

shocco_extract()
{
  local shocco_src_path="${src_path}/$(scm_identifier "${package_base_url}")/"
  ln -s ${shocco_src_path} "${src_path}/${extension}-head"
}
