#!/usr/bin/env bash

shocco_download()
{
  scm_fetch ${package_base_url}

}

shocco_extract()
{
  scm_update ${package_base_url}

  copy_paths --force "${repos_path}/${package_base_url//\//_}/" \
    to "${src_path}/${extension}-head"
}

