#!/usr/bin/env bash

number_of_args=${#extension_args[@]}

for ((index=0 ; index < $number_of_args ; index++)) ; do

  token="${extension_args[$index]}"

  case "$token" in
    --prefix)
      prefix_path="${extension_args[$((++index))]}"
      ;;
    --src)
      src_path="${extension_args[$((++index))]}"
      ;;
    --data)
      data_path="${extension_args[$((++index))]}"
      ;;
    --user)
      package_user="${extension_args[$((++index))]}"
      ;;
    --version)
      package_version="${extension_args[$((++index))]}"
      ;;
    --licence)
      cat -v "${extension_path}/LICENCE"
      exit 0
      ;;
    --help)
      usage
      exit 0
      ;;
    --trace)
      set -o xtrace
      ;;
    *)
      true # Ignore?
      ;;
  esac

done

