#!/usr/bin/env bash

display_install_message()
{
  log "

Message:

I am wayneeseguin in #rvm on irc.freenode.net and I am happy to discuss
improving this script, or field questions.

This script will now:

* Install ${package_name}-${package_version} to $install_path
* Put init script in place
* Add postgresql to ldconfig (Linux)
* Create and initialize data directory
* Setup profile.d script adding postgresql binaries to the path
* Add conf.d file allowing for server customization
* Adjust sysctl kernel parameters for postgresql (Linux)

"
}

postgresql_initialize()
{
  user_create_if_missing "$package_user"
  postgresql_initdb
  postgresql_init_script
  postgresql_conf_d
  postgresql_kernel_parameters

  log "
  Installation and configuration of postgresql is now complete.

  * postgresql has been installed to $install_path
  * postgresql configuration and data files will are in $data_path
  * You can control the postgresql server via the bdsm postgresql extension'
  * The postgersql superuser is '$package_user', no password.
  * Use /etc/conf.d/postgresql.conf for server startup customization.

  "
}

postgresql_kernel_parameters()
{
  true # TODO: Cross the finish line!!!
}

postgresql_initdb()
{
  log "Initializing postgresql data directory in $data_path"
  ensure_paths_exist "${data_path}"
  chown_paths_recursively "$package_user:$package_user" "${data_path}"

  command="'$install_path/bin/initdb' --pgdata='${data_path}/data' --encoding=utf8 --username=$package_user"

  if user_is_root
  then
    user_run_as "${package_user}" "${command}"
  else
    "${command}"
  fi

  chown_paths_recursively "$package_user:$package_user" "${data_path}"
  chmod_paths_recursively 0700 "${data_path}"

  postgresql_conf
}

postgresql_conf()
{
  local file
  log "Configuring postgresql server."

  ensure_paths_exist "${data_path}" "$log_path"

  link --force "${data_path}" to "${data_base_path}/active"

  for file in postgresql pg_hba pg_ident recovery
  do
    if file_is_empty_or_missing "$data_path/data/${file}.conf"
    then
      if file_is_missing "$data_path/data/${file}.conf.sample" ; then
        log "Missing $data_path/data/${file}.conf.sample, skipping."
        continue
      fi
      log "Installing ${file}.conf to ${data_path}/data/"

      copy_file "$data_path/data/${file}.conf.sample" \
        to "$data_path/data/${file}.conf"
    fi
  done

  chown_paths_recursively "$package_user" "$data_base_path"
  chmod_paths_recursively 0700 "$data_path"
}

postgresql_init_script()
{
  log "Installing Postgresql init script"
  install_template "postgresql" to "${init_scripts_path}/postgresql" mode 0755
}

postgresql_conf_d()
{
  if user_is_root
  then
    ensure_paths_exist "/etc/conf.d"

    log "Installing Postgresql conf.d script"

    install_template "postgresql.conf.d" \
      to "/etc/conf.d/postgresql.conf" \
      mode 0644
  fi
}

