#!/usr/bin/env bash

modules system package templates

define_package \
  version="$(hash_file "$extension_config_path/defaults" "version")" \
  archive_format="tar.bz2"

define_package \
  base_url="http://ftp9.us.postgresql.org/pub/mirrors/postgresql/source/v${package_version}" \
  target_path="${prefix_path}/${package_name}-${package_version}"

if running_as_root ; then
  pgsql_path="/data/postgresql-${version}"
  sudo=""
  postgresql_user="${postgresql_user:-postgres}"

  if [[ -d /etc/profile.d ]] ; then
    profiles=(/etc/profile.d/postgresql.sh)
  else
    if [[ -f /etc/bash.bashrc ]] ; then
      profiles=(/etc/bash.bashrc)
    else
      profiles=(/etc/bashrc)
    fi
  fi
  install_path="$prefix_path/$package-$version"
else
  sudo="sudo"
  true \
    "${postgresql_user:=$USER}" \
    "${prefix_path:="$HOME"}"
  true \
    "${pgsql_path:="$prefix_path/.postgresql-${version}"}" \
    "${profiles:=("$HOME/.bash_profile" "$HOME/.bashrc")}" \
    "${install_path:="$prefix_path/.$package-$version"}"
fi

ensure_user_exists "$postgresql_user"

true "${version:="9.0.3"}"

if [[ $UID -eq 0 ]] ; then
  "${prefix:=/usr/local}"
  true ${data_path:=/var/db/postgresql-${version}}
  log_path="/var/log/postgresql"
else
  prefix="${prefix:-$HOME/.pkg}"
  data_path="${data_path:-}"
fi

timestamp="$(date +"%Y-%m-%dT%H:%M")"
color_green="$(tput setaf 2)"
color_red="$(tput setaf 5)"
color_none="$(tput sgr0)"

