#!/usr/bin/env bash

modules package

package_definition \
  base_url "http://ftp9.us.postgresql.org/pub/mirrors/postgresql/source/v${package_version}"

if running_as_root ; then
  sudo=""

  read_default user prefix package

  if [[ -d /etc/profile.d ]] ; then
    profiles=(/etc/profile.d/postgresql.sh)
  else
    if [[ -f /etc/bash.bashrc ]] ; then
      profiles=(/etc/bash.bashrc)
    else
      profiles=(/etc/bashrc)
    fi
  fi
else
  sudo="sudo"

  true \
    "${package_user:=$USER}" \
    "${prefix_path:="$HOME/.bdsm"}"

  true \
    "${profiles:=("$HOME/.bash_profile" "$HOME/.bashrc")}"
fi

if [[ "${package_user}" = "postgresql" ]] ; then
  package_user="postgres"
fi

log_path="$data_path/log"

if [[ "$action" = *install ]] ; then
  configure_flags=(
    --prefix="${install_base_path}/${package_version}"
    --datadir="$data_path"
    --with-openssl
    --enable-shared
  )

  if os_is_darwin ; then
    configure_flags[${#configure_flags[@]}]="--with-bonjour"
  fi

  export CFLAGS='-O2'
fi

timestamp="$(date +"%Y-%m-%dT%H:%M")"

