#!/usr/bin/env bash

modules defaults package

read_default version into package_version

read_default base_url into package_base_url

define_package \
  file "otp_src_${package_version}.${archive_format}" \
  dir "otp_src_${package_version}"

dependencies=( ncurses openssl )

configure_flags=(
  --enable-hipe
  --enable-smp-support
  --enable-threads
  --enable-kernel-poll
)

if os_is_darwin ; then
  configure_flags[${#configure_flags[@]}]="--enable-darwin-64bit"
fi
