#!/usr/bin/env bash

modules defaults package

read_default version prefix package
read_default base_url prefix package

package_definition \
  dir "sqlite-autoconf-${package_version}" \
  file "sqlite-autoconf-${package_version}.tar.gz"

