#!/usr/bin/env bash

modules package

# TODO: Make version configurable from ~/.bdsm/${extension}/config

define_package \
  name "sqlite" \
  version "3070500"

# We specify the package_file here since it is different than the standard name-version.tar.gz
define_package \
  url "http://www.sqlite.org/${package_name}-autoconf-${package_version}.${archive_extension}" \
  file "${package_name}-autoconf-${package_version}.${archive_extension}"

