#!/usr/bin/env bash

unrar_configure()
{
  replace_content "^DESTDIR=.*$" \
    with "DESTDIR=${install_path}" \
    in "makefile.unix"
}

unrar_extract()
{
  if directory_exists "unrar"
  then
    remove_paths "unrar"
  fi

  tar zxf ${package_file}

  move_directory "unrar" to "${package_dir}"
}

unrar_build()
{
  make --makefile makefile.unix
}

unrar_install()
{
  ensure_paths_exist "${install_path}/bin"
  move_file "unrar" to "${install_path}/bin/unrar"
  ensure_files_are_executable "${install_path}/bin/unrar"
}

