#!/usr/bin/env bash

modules package

# TODO: Make version configurable from ~/.bdsm/${extension}/config

package_definition \
  version "1.13.1" \
  file "libiconv-1.13.1.tar.gz" \
  dir "libiconv-1.13.1" \
  base_url "http://ftp.gnu.org/pub/gnu/libiconv"

