#!/usr/bin/env bash

elasticsearch_configure()
{
  : # Beautifully, nothing to do here :)
}

elasticsearch_build()
{
  : # Nothing to do here, either!
}

elasticsearch_install()
{
  ensure_paths_exist "${package_dir}"
  copy_paths --force to "${install_path}/" "${package_dir}"
}
