#!/usr/bin/env bash

modules defaults package

read_default version prefix package
read_default base_url prefix package

package_definition \
  file "${package_name}-src-${package_version}.${archive_format}" \
  dir "${package_name}-src-${package_version}"

