#!/usr/bin/env bash

description "Extension for managing mongrel2 ()."

action "service start" "Starts mongrel2 service."
action "service stop" "Stop mongrel2 service."
action "service restart" "Restarts mongrel2 service."
action "service status" "Display mongrel2 status."
action "service list" "List mongrel2 master and worker processes."

show_help usage

