#!/usr/bin/env bash

description "${extension} BDSM extension."

action "package [action]" "Perform ${extension} package action {install,uninstall}"
action "help" "Display help for ${extension}."

show_help usage
