#!/usr/bin/env bash

if os_is_darwin
then
  os_type="mac"
  archive_format="zip"
elif os_is_linux
then
  os_type="linux"
  archive_format="tgz"
else
  error "Only Darwin and Linux are currently supported for ${extension}."
fi

package_definition \
  file "android-sdk_${package_version}-${os_type}_x86.${archive_format}" \
  dir "android-sdk-${os_type}_x86"

