#!/usr/bin/env bash

modules package

# TODO: Make version configurable from ~/.bdsm/${extension}/config

package_definition \
  version "4.0.3" \
  archive_format "tar.gz" \
  base_url "http://mirrors.kernel.org/gnu/${package_name}"

