#!/usr/bin/env bash

modules core/package

#package_dependencies=(python-2.*)
if ! (command_exists python2 || command_exists python2.7 || command_exists python2.5)
then
  error "node package depends on python 2 in order to build, install python package version 2"
fi

package_definition \
  base_url "http://nodejs.org/dist/v${package_version}" \
  file "${package_name}-v${package_version}.${archive_format}" \
  dir "${package_name}-v${package_version}"

