#!/usr/bin/env bash

modules package

package_dependencies=(python-2)

package_definition \
  file "${package_name}-v${package_version}.${archive_format}"\
  dir "${package_name}-v${package_version}"\

