#!/usr/bin/env bash

# Load RVM if it is found
files=( "$rvm_path/scripts/rvm" "$HOME/.rvm/scripts/rvm" "/usr/local/scripts/rvm" )
source_files $(first $(nonempty_files "${files[@]}"))

# Load environment and bdsmrc files.
files=("$HOME/.bashrc" "/etc/bdsmrc" "$HOME/.bdsmrc" )
source_files "${files[@]}"

true \
  "${discard_path:="$shared_path/discard"}" \
  "${previous_path:=${project_path}/previous}" \
  "${stage_path:=${project_path}/stage}"


ensure_paths_exist \
  "$previous_path" \
  "$discard_path"

previous="$(\ls -t "$previous_path"/ | head -1)"
