#!/usr/bin/env bash

log()  { printf "$*\n" ; return $? ;  }

fail() { log "\nERROR: $*\n" ; exit 1 ; }

shopt -s extglob # Extended globs
set -o errtrace

export PS4='+[${BASH_SOURCE}] : ${LINENO} : ${FUNCNAME[0]:+${FUNCNAME[0]}() $ }'

[[ ${trace_flag:-0} -eq 1 ]] && set -o xtrace
[[ ${debug_flag:-0} -eq 1 ]] && set -o verbose

# Load RVM if it is found
files=( "$rvm_path/scripts/rvm" "$HOME/.rvm/scripts/rvm" "/usr/local/scripts/rvm" )

for file in "${files[@]}" ; do
  if [[ -s "$file" ]] ; then
    source "$file"
    break # stop after loading first one found.
  fi
done

# Load environment and bdsmrc files.
files=("$HOME/.bashrc" "/etc/bdsmrc" "$HOME/.bdsmrc" )

for file in "${files[@]}" ; do
  [[ -s "$file" ]] && source "$file"
done
