#!/usr/bin/env bash

upgrade_binary()
{
  original_binary="${prefix_path}/bin/${extension}"

  if [[ -x "$original_binary" ]] ; then
    original_version=$("$original_binary" -c 'printf $ZSH_VERSION')

    log "Preserving old binary as '$original_binary-$original_version'..."

    move_file "${original_binary}" to "${original_binary}-$original_version"
  fi
}

