#!/usr/bin/env bash

modules defaults package

dependencies \
  iconv

read_default version prefix package
read_default archive_format

package_definition \
  base_url "http://cdnetworks-us-1.dl.sourceforge.net/project/zsh/zsh-dev/${package_version}"

