#!/usr/bin/env bash

modules package

dependencies \
  iconv

package_definition \
  version "4.3.11" \
  archive_format "tar.bz2"

package_definition \
  base_url "http://cdnetworks-us-1.dl.sourceforge.net/project/zsh/zsh-dev/${package_version}"

