#!/usr/bin/env bash

description "Extension for managing Nginx (http://wiki.nginx.org/Main)."

action "start" "Startup ${extension}."
action "stop" "Stop ${extension}."
action "status" "Display ${extension} status."
action "list" "List ${extension} master and worker processes."
action "restart" "Restart ${extension}."

show_help usage
