#!/usr/bin/env bash

description "Extension for managing Nginx (http://wiki.nginx.org/Main)."

action "start" "Startup nginx."
action "stop" "Stop nginx."
action "status" "Display Nginx status."
action "list" "List nginx master and worker processes."
action "restart" "Restart nginx."

show_help usage
