#!/usr/bin/env bash

modules package

# TODO: Make version configurable from ~/.bdsm/${extension}/config

define_package \
  version "0.17" \
  base_url "http://jonas.nitro.dk/tig/releases" \
  md5_url "http://jonas.nitro.dk/tig/releases"
