#!/usr/bin/env bash

node_configure()
{
  if os_is_linux
  then
    if command_exists python2
    then
      replace_content "\#!/usr/bin/env python" \
        with "\#!$(command -v python2)" in "tools/waf-light"

      replace_content "\#!/usr/bin/env python" \
        with "\#!$(command -v python2)" in "tools/wafadmin/Scripting.py"
    fi
  fi
  ./configure --prefix="${install_path}"
}

