#!/usr/bin/env bash

set -o errtrace
export PS4='+${BASH_SOURCE} : ${LINENO} : ${FUNCNAME[0]:+${FUNCNAME[0]}() : }'

if [[ $UID -eq 0 ]] ; then
  prefix_path="${prefix_path:-"/usr/local"}"
  src_path="$prefix_path/src"
  pgsql_path="/data/postgresql-${version}"
  sudo=""
  user="${user:-postgres}"

  if [[ -d /etc/profile.d ]] ; then
    profiles=(/etc/profile.d/postgresql.sh)
  else
    if [[ -f /etc/bash.bashrc ]] ; then
      profiles=(/etc/bash.bashrc)
    else
      profiles=(/etc/bashrc)
    fi
  fi
  install_path="$prefix_path/$package-$version"
else
  prefix_path="${prefix_path:-"$HOME"}"
  src_path="${src_path:-"$prefix_path/.src"}"
  pgsql_path="$prefix_path/.postgresql-${version}"
  sudo="sudo"
  user="${user:-$USER}"
  profiles=("$HOME/.bash_profile" "$HOME/.bashrc")
  install_path="$prefix_path/.$package-$version"
fi

if [[ $UID -eq 0 ]] ; then
  # TODO: correct this for multiple OS types.
  if useradd -r "$user" ; then
    echo "User $user added."
  else
    echo "User $user already exists."
  fi
fi

timestamp="$(date +"%Y-%m-%dT%H:%M")"
color_green="$(tput setaf 2)"
color_red="$(tput setaf 5)"
color_none="$(tput sgr0)"
system="postgresql"
version="${version:-"$($scripts_path/db "$extension_path/config/db" "version")"}"

package="postgresql"
version="9.0.3"
archive_format="tar.bz2"
url="http://ftp9.us.postgresql.org/pub/mirrors/postgresql/source/v${version}"


if [[ $UID -eq 0 ]] ; then
  "${prefix:=/usr/local}"
  true ${data_path:=/var/db/postgresql-${version}}
  log_path="/var/log/postgresql"
else
  prefix="${prefix:-$HOME/.pkg}"
  data_path="${data_path:-}"
fi

mkdir -p $log_path $data_path

install_path="$prefix/postgresql-$version"

