#!/usr/bin/env bash

modules package

# TODO: Make version configurable from ~/.bdsm/curl/config
define_package \
  version "7.21.4" \
  archive_format "tar.bz2" \
  base_url "http://curl.haxx.se/download"

