#!/usr/bin/env bash

echo "Example: nonempty_files()"

echo "Testing if ~/.bdsmrc is nonempty"
if file_is_nonempty "$HOME/.bdsmrc"
then
  echo "The file is nonempty"
else
  echo "The file is empty"
fi

