#!/usr/bin/env bash

mongrel2_configure()
{
  true
}

mongrel2_build()
{
  OPTFLAGS="-I${active_path}/include" OPTLIBS="-L${active_path}/lib" \
    PREFIX="${install_path}" make all
}

mongrel2_install()
{

  OPTFLAGS="-I${active_path}/include" OPTLIBS="-L${active_path}/lib" \
    PREFIX="${install_path}" make install
}

