#!/usr/bin/env bash

mongrel2_configure()
{
  true
}

mongrel2_build()
{
  CLFAGS="-I${active_path}/include" LDFLAGS="-L${active_path}/lib" \
    PREFIX="${install_path}" make > make.log 2>&1
}

mongrel2_install()
{

  CLFAGS="-I${active_path}/include" LDFLAGS="-L${active_path}/lib" \
    PREFIX="${install_path}" make install > make.install.log 2>&1
}

