#!/usr/bin/env bash

setup_redis_user()
{
  if [[ $UID -eq 0 ]] ; then
    (
    case "$(uname)" in
      "OpenBSD")
        groupadd "$redis_user"
        useradd -g "$redis_user" "$redis_user" -s /bin/bash
        usermod -s /bin/bash "$redis_user"
        ;;
      "FreeBSD")
        pw groupadd -q "$redis_user"
        ;;
      "Linux")
        if [[ -f "/etc/SuSE-release" ]] ; then
          groupadd "$redis_user"
        else
          groupadd -f "$redis_user"
        fi
        useradd -g "$redis_user" -s /bin/bash -d /var/lib/redis "$redis_user"
        usermod -s /bin/bash "$redis_user"
      ;;

      "Darwin")
        gid="501" #only gids > 500 show up in user preferences

        #Find an open gid
        while true; do
          name=$(dscl . search /groups PrimaryGroupID $gid | cut -f1 -s)
          if [ -z "$name" ] ; then
            break
          fi
          gid=$[$gid +1]
        done

        #Create the group
        dscl . -create "/Groups/$redis_user"
        dscl . -create "/Groups/$redis_user" gid "$gid"

        # ????
        # useradd -g "$redis_user" -s /bin/bash -d /var/lib/redis "$redis_user"
        # usermod -s /bin/bash
      ;;
      "SunOS")
        groupadd "$redis_user"
        useradd -g "$redis_user" -s /bin/bash -d /var/lib/redis "$redis_user"
        usermod -s /bin/bash "$redis_user"
        ;;
    esac
    ) || true # Ignore failures with this for now...

  fi
  return 0
}

create_redis_directories()
{
  local directory redis_path

  # TODO: can likely merge directory creation into path creation.

  log "#creating paths for ${package} ${package_version}..."

  ensure_paths_exist "${directories[@]}"

  chown_paths "$redis_user" "${directories[@]}"

  ensure_paths_exist "${redis_paths[@]}"

  chown_paths "$redis_user" "${redis_paths[@]}"

  ensure_paths_exist "${redis_install_path}"
}

install_init_script()
{
  log "#installing init script"

  install_template "redis" to "${init_scripts_path}/redis"

  ensure_files_are_executable "${init_scripts_path}/redis"

  # Add to system startup
  if [[ $UID -eq 0 ]] ; then
    if command -v rc-update >/dev/null 2>&1 ; then
      rc-update add redis default
    elif command -v chkconfig >/dev/null 2>&1 ; then
      chkconfig redis on
    else
      # Falling back on rc.local to start redis at system startup.
      echo "${init_scripts_path}/redis start" >> /etc/rc.local
    fi
  fi

  return 0
}

install_redis_conf()
{
  if [[ -s "${redis_config_file}" ]] ; then
    log "${redis_config_file} already exists, not overwriting."
  else
    log "#installing redis.conf file to ${redis_config_file}"

    sed -e "s#pidfile .*\$#pidfile ${redis_pid_file}#" \
        -e "s#logfile .*\$#logfile ${redis_log_file}#" \
        -e "s#dir .*\$#dir ${redis_db_path}#" \
        -e "s#^.*daemonize .*\$#daemonize yes#" \
        -e "s#dbfilename .*\$#dbfilename ${redis_db_file}#" \
        -e "s#port .*\$#port ${redis_port}#" \
        -e "s#bind .*\$#bind ${redis_bind_interface}#" \
      "${redis_src_path}/redis.conf" > "${redis_config_file}"

    chown -R $redis_user "${redis_config_file}"
  fi
  return 0
}

cleanup()
{
  log "#cleaning install files for ${package} ${package_version}...\n"
  enter "${src_path}"

  local files=($(
  find "$src_path/" -mindepth 1 -maxdepth 1 -iname "${package}-${package_version}*"
  ))

  remove_files "${files[@]}"
}

download_redis()
{
  ensure_paths_exist "${src_path}"

  enter "${src_path}"

  log "#downloading ${package_file}...\n"

  if ! curl -O -L "${package_url}" ; then
    fail "${package_file} failed to download from '${package_url}'."
  fi
}

extract_redis()
{
  enter "${src_path}"

  log "#extracting ${package} ${package_version}...\n"

  if ! tar zxf "${package_file}" ; then
    fail "${package_file} failed to extract."
  fi

  return 0
}

build_redis()
{
  enter "${src_path}"

  # Nothing to configure, proceeding straight to make.

  log "#compiling ${package} ${package_version}...\n"

  if ! make 2>&1 > "${redis_src_path}/make.log" ; then
    fail "Compiling ${package}-${package_version} failed, see ${redis_src_path}/make.log"
  fi
}

install_redis()
{
  log "#installing ${package} ${package_version}...\n"

  for file in redis-server redis-cli ; do
    if ! install -b "${redis_src_path}/src/${file}" "${redis_bin_path}/${file}" ; then
      fail "${package} ${package_version} failed to install (specifically ${file}).\n"
    fi
  done
}

