#!/usr/bin/env bash

modules rvm package service

# Redis Configuration.
true ${redis_user:=redis}
true ${redis_port:=6379}
true ${redis_bind_interface:="127.0.0.1"}
true ${redis_src_path:="${source_path}/${package}-${version}"}
true ${redis_install_path:="$prefix"}
true ${redis_bin_path:="${redis_install_path}/bin"}
true ${redis_config_path:="/etc/redis"}
true ${redis_config_file:="${redis_config_path}/redis.conf"}
true ${redis_servers_path:="$redis_etc_path/servers"}
true ${redis_log_path:="/var/log/redis"}
true ${redis_log_file:="/var/log/redis/redis.log"}
true ${redis_server_binary:="${redis_bin_path}/redis-server"}
true ${redis_cli_binary:="${redis_bin_path}/redis-cli"}
true ${redis_pid_path:="/var/run/redis"}
true ${redis_pid_file:="${redis_pid_path}/redis.pid"}
true ${redis_db_path:="/var/db/redis"}
true ${redis_db_file:="${redis_db_path}/dump.rdb"}
true ${redis_lock_path:="/var/lock/redis"}
true ${redis_lock_file:="${redis_lock_path}/redis.lock"}
true ${init_scripts_path:="$(init_scripts_path)"}

redis_paths=(
  "${redis_bin_path}"
  "${redis_config_path}"
  "${redis_pid_path}"
  "${redis_db_path}"
  "${redis_lock_path}"
  "${redis_servers_path}"
  "${redis_log_path}"
)

