#!/usr/bin/env bash

modules package

# TODO: Make version configurable from ~/.bdsm/${extension}/config

define_package \
  version "8.1.2" \
  base_url "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre"

