#!/usr/bin/env bash

description "Extension for managing ${extension} (${website_url})."

action "start" "Startup ${extension}."
action "stop" "Stop ${extension}."
action "restart" "Restart ${extension}."
action "status" "Display ${extension} status."
action "list" "List ${extension} master and worker processes."

show_help usage

