#!/usr/bin/env bash

set_master_pid()
{
# Fetch the running pid.
if variable_is_nonempty project
then
  running_pid=$(
  ps auxww | awk "/[u]nicorn master/ && ! /(old)/ && /\/${project}\// {print \$2}"
  )

  old_pid=$(
  ps auxww | awk "/[u]nicorn master/ && /(old)/ && /\/${project}\// {print \$2}"
  )
else
  running_pid=$(
  ps auxww | awk "/[u]nicorn master/ && ! /(old)/ && /\/${USER}\// {print \$2}"
  )
  old_pid=$(
  ps auxww | awk "/[u]nicorn master/ && /(old)/ && /\/${USER}\// {print \$2}"
  )

  log "WARNING: 'project' should be set in ~/.bdsmrc"
fi

if (( running_pid > 0 )) && [[ -d "/proc/${running_pid}" ]]
then
  echo ${running_pid} > "$pid_file" # Make sure the correct running pid is in the pid_file.
  master_pid=${running_pid} # Set to the found running pid_file.

elif (( pid_file_pid > 0 )) && [[ -d "/proc/${pid_file_pid}" ]]
then
  master_pid=${pid_file_pid} # Running and matches pid_file.
else
  master_pid=0 # Not found!
fi

}

