#!/usr/bin/env bash

modules defaults package

dependencies=( libevent )

read_default version prefix package

package_definition \
  base_url "http://cdnetworks-us-2.dl.sourceforge.net/project/tmux/tmux/tmux-${package_version}"

