#!/usr/bin/env bash

p7zip_configure()
{
  log "Configuring ${package_name} ${package_version}"
  case "$(os_arch_capable)" in
    x86_64)
      move_file "makefile.macosx_64bits" to "makefile.machine"
      ;;
    *)
      move_file "makefile.macosx_32bits" to "makefile.machine"
      ;;
  esac
}

p7zip_build()
{
  log "Building ${package_name} ${package_version}"
  make ${make_flags:-} all3 > make.log
}

p7zip_install()
{
  make DEST_HOME="${install_path}" DEST_MAN="${install_path}/man" install > make.install.log
  log "Installed ${package_name} ${package_version}"
}
