#!/usr/bin/env bash

p7zip_configure()
{
  local _machine=""

  log "Configuring ${package_name} ${package_version}"

  if os_is_darwin ; then
    case "$(os_arch_capable)" in
      x86_64)
        _machine="macosx_64bits"
        ;;
      *)
        _machine="macosx_32bits"
        ;;
    esac
  elif os_is_linux ; then
    case "$(os_arch_capable)" in
      x86_64)
        _machine="linux_amd64"
        ;;
      *)
        _machine="linux_any_cpu"
        ;;
    esac
  fi

  variable_is_nonempty "_machine" ||
    fail "Cannot configure ${package_name} ${package_version}, currently unhandled machine type for extension ${p7zip}."

  move_file "${source_path}/${package_dir}/makefile.${_machine}" \
    to "${source_path}/${package_dir}/makefile.machine"
}

p7zip_build()
{
  log "Building ${package_name} ${package_version}"
  make ${make_flags:-} all3 > make.log
}

p7zip_install()
{
  make DEST_HOME="${install_path}" DEST_MAN="${install_path}/man" install > make.install.log
  log "Installed ${package_name} ${package_version}"
}
