#!/usr/bin/env bash

set -o errtrace
export PS4='+[${BASH_SOURCE}] : ${LINENO} : ${FUNCNAME[0]:+${FUNCNAME[0]}() $ }'

[[ ${trace_flag:-0} -eq 1 ]] && set -o xtrace
[[ ${debug_flag:-0} -eq 1 ]] && set -o verbose

bdsmrc

export PATH="/sbin:/usr/sbin:/usr/local/sbin:/opt/sbin:/opt/local:sbin:$PATH"

master_pid="$(ps auxww |  awk '/[n]ginx: master/{print $2}' | head -n 1)"

init_scripts_path=$(init_scripts_path)

nginx_install_path="/usr/local/nginx"
nginx_config_file="${nginx_config_file:-"/etc/nginx/nginx.conf"}"
nginx_path="/etc/nginx"
nginx_config_path="$nginx_path/conf"
nginx_servers_path="$nginx_path/servers"
nginx_binary="/usr/sbin/nginx"
nginx_pid_file="/var/run/nginx.pid"
nginx_lock_file="/var/lock/nginx.lock"
nginx_spool_path="/var/spool/nginx"
nginx_log_path="/var/log/nginx"

