#!/usr/bin/env bash
description "Extension for managing pypy ${website_url:-}."

action "package install" "Installs pypy package."
action "package uninstall" "Uninstalls pypy package."

show_help usage

