#!/usr/bin/env bash

description "Extension for managing rainbows (http://rainbows.bogomips.org/)."

action "install" "Installs ${package_name} gem."
action "setup" "Setup the rainbows config file with a template in $release_path/config/"
action "start" "Start."
action "stop" "Stop."
action "restart" "Restart."
action "reload" "Reload rainbows configuration file."
action "logs" "Reopen log files."
action "increase" "Increase the number of rainbows worker processes."
action "decrease" "Decrease the number of rainbows worker processes."
action "terminate" "Force kill rainbows master."
action "list" "List all running rainbowss for $project $environment."
action "pause" "Pause all rainbows workers."
action "unpause" "Unpause all rainbows workers."
action "help" "Display this help text."

show_help usage

