#!/usr/bin/env bash

[[ ${master_pid} -gt 0 ]] || \
  succeed "There are no rainbowss running for $project."

if [[ -n "${project:-}" ]] ; then
  ps auxww | awk "/[r]ainbows/ && /master/ && /${project}/"
  ps auxww | awk "/[r]ainbows/ && /worker/ && /${project}/"
else
  ps auxww | awk "/[r]ainbows/ && /master/ && /${USER}/"
  ps auxww | awk "/[r]ainbows/ && /worker/ && /${USER}/"
fi

