#!/usr/bin/env bash

if [[ ${master_pid} -le 0 ]] ; then
  log "rainbows herd master not found running for $project $environment, starting."

  [[ -s "$release_path/config/rainbows.rb" ]] || \
    fail "config/rainbows.rb not found, aborting start."

  file_is_nonempty "$release_path/config.ru" || binary="rainbows_rails"

  ${binary:-rainbows} -c "$release_path/config/rainbows.rb" -E "$environment" -D

else
  log "Master pid '$master_pid' found."

  log "Signaling herd master '$master_pid' for $project $environment to re-execute the running binary."

  kill -USR2 ${master_pid}

  log "Signaled rainbows master '$master_pid' for $project $environment, it should restart within a few seconds. As requests finish processing workers will be replaced."
fi
