#!/usr/bin/env bash

nginx_configure()
{
  if gcc --version | grep '4.6' > /dev/null 2>&1
  then
    if variable_is_nonempty CFLAGS
    then # Adjust for gcc 4.6 strictness.
      export CFLAGS="-Wunused-but-set-variable ${CFLAGS}"
    else
      export CFLAGS="-Wunused-but-set-variable"
    fi
  fi

  package_configure
}

configure_nginx()
{
  (
  enter "${active_path}"
  ensure_paths_exist "${config_directories[@]}"
  )

  (
  # Cleanup default nginx install messy directory.
  enter "${active_path}/nginx"
  move_files to "${active_path}/config" "${nginx_files[@]}"
  )

  ensure_paths_exist "${active_path}/config" "${nginx_servers_path}"

  install_template "nginx.conf" to "${active_path}/nginx/nginx.conf" \
    mode 0644 owner "${nginx_user}"

  install_template "nginx" to "${init_scripts_path}/nginx" \
    mode 0755 owner "${nginx_user}"

  templates=( "mime.types" "proxy.conf" )
  for template in "${templates[@]}"
  do
    install_template "${template}" to "${active_path}/nginx/${template}" \
      mode 0644 owner "${nginx_user}"
  done

  user_create_if_missing "nginx" with group "nginx"

  if user_is_root
  then
    if (( ${force_flag:-0} == 1 ))
    then
      remove_paths "/etc/nginx"
    fi

    if ! file_exists "/etc/nginx/nginx.conf"
    then
      link --force "${active_path}/nginx" "/etc/nginx"
    fi
    link --force "${active_path}/sbin/nginx" to "/usr/sbin/nginx"
  fi

  chown_paths_recursively "nginx:nginx" "${config_directories[@]}"
}
