#!/usr/bin/env bash

modules defaults package

export PATH="/sbin:/usr/sbin:/usr/local/sbin:/opt/sbin:/opt/local:sbin:$PATH"

init_scripts_path=$(init_scripts_path)

true ${nginx_path:="/etc/nginx"}

true \
  ${nginx_config_file:="${nginx_path}/nginx.conf"} \
  ${nginx_config_path:="${nginx_path}/conf"} \
  ${nginx_servers_path:="${nginx_path}/servers"} \
  ${nginx_binary:="${install_path}/bin/nginx"} \
  ${nginx_pid_file:="/var/run/nginx.pid"} \
  ${nginx_lock_file:="/var/lock/nginx.lock"} \
  ${nginx_spool_path:="/var/spool/nginx"} \
  ${nginx_log_path:="/var/log/nginx"}

configure_flags=(--prefix="$install_path"
  --conf-path="$nginx_config_file"
  --sbin-path="$nginx_binary"
  --pid-path="$nginx_pid_file"
  --lock-path="$nginx_lock_file"
  --http-client-body-temp-path="$nginx_spool_path/client_body_temp"
  --http-proxy-temp-path="$nginx_spool_path/proxy_temp"
  --http-fastcgi-temp-path="$nginx_spool_path/fastcgi_temp"
  --http-log-path="$nginx_log_path/access.log"
  --error-log-path="$nginx_log_path/error.log"
  --with-imap
  --with-imap_ssl_module
  --with-http_ssl_module
  --with-http_stub_status_module
  --with-pcre
)

config_directories=(/var/spool/nginx/client_body_temp
/var/log/nginx
"$nginx_config_path/conf"
"$nginx_config_path/servers"
)

nginx_files=( fastcgi.conf fastcgi.conf.default fastcgi_params
fastcgi_params.default koi-utf koi-win mime.types mime.types.default
nginx.conf.default scgi_params scgi_params.default uwsgi_params
uwsgi_params.default win-utf
)

master_pid="$(ps auxww | awk '/[n]ginx: master/{print $2}' | head -1)"

