#!/usr/bin/env bash

description "${extension} BDSM extension."

actions "install" "Install $extension ."
action "setup" "Setup and Configure $extension."
action "start" "Start ${extensoin}."
action "stop" "Stop ${extension}."
action "restart" "Restart ${extension}."
action "status" "Display ${extension} status."

show_help usage
