#!/usr/bin/env bash

description "${extension} BDSM extension."

action "package [action]" "Take Package action {install,uninstall}"
action "service [action]" "NIY"
action "help" "Display help for ${extension}."

show_help usage
