#!/usr/bin/env bash

description "Extension for managing elasticsearch ()."

action "service start" "Starts elasticsearch service."
action "service stop" "Stop elasticsearch service."
action "service restart" "Restarts elasticsearch service."
action "service status" "Display elasticsearch status."
action "service list" "List elasticsearch master and worker processes."

show_help usage

