#!/usr/bin/env bash

patch_package()
{
  local patch_name patches=$(curl -s -l "${package_patches_url}/" | grep -v .sig)

  for patch_name in "${patches[@]}" ; do
    log "Applying Patch ${patch_name}..."

    patch -p0 < <(curl -s "${package_patches_url}/${patch_name}")
  done
}

upgrade_bash()
{
  original_binary="${prefix_path}/bin/bash"

  if [[ -x "$original_binary" ]] ; then
    original_version=$("$original_binary" -c 'printf ${BASH_VERSION//\(*}')

    log "Preserving old binary as '$original_binary-$original_version'..."

    move_file "${original_binary}" to "${original_binary}-${original_version}"
  fi
}

