#!/usr/bin/env bash

modules defaults package

read_default version prefix package
read_default base_url prefix package

package_definition \
  patches_url "ftp://ftp.gnu.org/gnu/bash/bash-${package_version}-patches"

