#!/usr/bin/env bash

modules package

define_package \
  version "4.2" \
  base_url "ftp://ftp.gnu.org/gnu/bash"

define_package \
  patches_url "ftp://ftp.gnu.org/gnu/bash/bash-${package_version}-patches"

