#!/usr/bin/env bash

# TODO: deal with mysql version_greater_than "5.5", eg. cmake etc...
# This function must: configure, build, install to ${install_path}
# TODO: adjust this for new cmake install method.
# http://dev.mysql.com/doc/refman/5.5/en/source-configuration-options.html
# http://dev.mysql.com/doc/refman/5.5/en/installing-source-distribution.html

mysql_initialize()
{
  user_create_if_missing "${package_user}"

  mysql_initdb

  mysql_init_script

  mysql_conf_d

  log "
  Installation and configuration of mysql is now complete.

  * mysql has been installed to $install_path
  * mysql configuration and data files will are in $service_data_path
  * You can control the mysql server via the bdsm mysql extension'
  * The mysql superuser is '$package_user', no password.
  * Use /etc/conf.d/mysql.conf for server startup customization.

"
}

mysql_initdb()
{
  log "Initializing mysql data directory in $service_data_path"

  ensure_paths_exist "${service_data_path%\/*}"

  chown_paths_recursively "$package_user" "${service_data_path%\/*}"

  command="${install_path}/bin/mysql_install_db --user=\"${package_user}\" --basedir=\"${install_path}\" --datadir=${service_data_path} "
  # --srcdir=\"${source_path}/${package_name}-${package_version}\"
  export PATH="${install_path}/bin:$PATH"

  if user_is_root
  then
    user_run_as "${package_user}" "${command}"
  else
    "${command}"
  fi

  mysql_postinstall
}

mysql_postinstall()
{
  local file

  log "Configuring mysql server."

  # TODO: Is this not done in package_install ??? vvv
  link --force "${service_data_path}" to "${service_data_path%\/*}/data"

  if [[ -s "/etc/mysql/my.cnf" ]] ; then
    log "Skipping /etc/mysql/my.cnf as it already exists, use bdsm mysql configure to override later."
  else
    # TODO: Determine which .cnf file to grab based on system resources.
    file="${source_path}/${package_dir}/support-files/my-medium.cnf"
    if [[ -s "${file}" ]] ; then
      log "Installing my.cnf to /etc/mysql"
      cp -f "${file}" "/etc/mysql/my.cnf"
    else
      log "ERROR: ${file} missing, not setting up /etc/mysql/my.cnf"
    fi
  fi

  log "\nSymlinking $install_path to $prefix_path/mysql"

  remove_paths "$prefix_path/mysql"

  ensure_paths_exist "$service_data_path" "$log_path" "/etc/mysql/"

  chown_paths_recursively "$package_user" "$service_data_path"

  chmod_paths_recursively 0700 "$service_data_path"
}

mysql_init_script()
{
  log "Installing mysql init script"
  install_template "mysql" to "${init_scripts_path}/mysql" mode 0755
}

mysql_conf_d()
{
  log "Installing mysql conf.d script"
  install_template "mysql.conf.d" to "${confd_path}/mysql.conf" mode 0644
}

