#!/usr/bin/env bash

mysql_initdb()
{
  log "Initializing mysql data directory in $data_path"

  ensure_paths_exist "${data_path%\/*}"

  chown_paths "$package_user" \
    "${data_path%\/*}"

  command="${install_path}/bin/mysql_install_db --user=${package_user} --basedir=${data_path%\/*} --datadir=${data_path}"

  (
    enter "${install_path}" # Combat poorly written mysql_install_db script.

    export PATH="${install_path}/bin:$PATH"

    if running_as_root ; then
      run_as_user "${package_user}" "${command}"
    else
      "${command}"
    fi

    mysql_configure
  )
}

mysql_configure()
{
  local file

  log "Configuring mysql server."

  link --force "${data_path}" \
    to "${data_path%\/*}/data"

  # TODO: Determine which .cnf file to grab based on system resources.
  file="${source_path}/${package_dir}support-files/my-medium.cnf"
  if [[ -s "${file}" ]] ; then
    log "Installing my.cnf to /etc/mysql"
    cp -f "${file}" "/etc/mysql/my.cnf"
  fi

  log "\nSymlinking $install_path to $prefix_path/mysql"

  remove_paths \
    "$prefix_path/mysql"

  link "$install_path" \
    to "$prefix_path/mysql"

  ensure_paths_exist \
    "$data_path" \
    "$log_path" \
    "/etc/mysql/"

  chown_paths "$package_user" \
    "$data_path"

  chmod_paths 0700 \
    "$data_path"
}

mysql_ldconfig()
{
  log "Adding mysql libraries to system ld path."

  if running_as_root && os_is_linux ; then
    echo "${prefix_path}/mysql/lib" \
      > /etc/ld.so.conf.d/mysql.conf

    chmod_paths 0644 \
      "/etc/ld.so.conf.d/mysql.conf"

    /sbin/ldconfig
  fi
}

mysql_init_script()
{
  log "Installing mysql init script"
  install_template "mysql" \
    to "${init_scripts_path}/mysql"

  ensure_files_are_executable \
    "${init_scripts_path}/mysql"

  chmod_paths 0755 \
    "${init_scripts_path}/mysql"
}

mysql_profile_d()
{
  if running_as_root && os_is_linux ; then
    log "Installing mysql profile.d script"

    install_template "mysql.sh" \
      to "/etc/profile.d/mysql.sh"

    chmod_paths 0755 \
      "/etc/profile.d/mysql.sh"
  fi
}

mysql_conf_d()
{
  if running_as_root && os_is_linux ; then
    log "Installing mysql conf.d script"

    install_template "mysql.conf.d" \
      to "/etc/conf.d/mysql.conf"

    chmod_paths 0644 \
      "/etc/conf.d/mysql.conf"
  fi
}

