#!/usr/bin/env bash

modules defaults package

read_defaults version into package_version

define_package \
  base_url "http://mysql.mirrors.pair.com/Downloads/MySQL-${package_version%.*}" \
  target_path "${prefix_path}/${package_name}-${package_version}"

if running_as_root ; then

  data_path="/var/db/${package_name}/${package_version}"

  sudo=""

  if [[ -d /etc/profile.d ]] ; then
    profiles=(/etc/profile.d/mysql.sh)
  else
    if [[ -f /etc/bash.bashrc ]] ; then
      profiles=(/etc/bash.bashrc)
    else
      profiles=(/etc/bashrc)
    fi
  fi

  install_path="${prefix_path}/${package_name}-${package_version}"
else
  sudo="sudo"

  true \
    "${package_user:=$USER}" \
    "${prefix_path:="$HOME"}"

  true \
    "${data_path:="$prefix_path/.${package_name}-${package_version}"}" \
    "${profiles:=("$HOME/.bash_profile" "$HOME/.bashrc")}" \
    "${install_path:="$prefix_path/.${package_name}-${package_version}"}"
fi

log_path="$data_path/log"

if [[ "$action" = *install ]] ; then
  # TODO: configure flags per OS.
  # http://dev.mysql.com/doc/refman/5.1/en/source-configuration-options.html
  configure_flags=(
    --prefix="${install_path}"
    --localstatedir="${data_path}"
    --enable-assembler
    --with-mysqld-ldflags=-all-static
    --with-charset=utf8
    --with-collation=utf8_general_ci
  )
  export CFLAGS="-O3"
  export CXX=gcc
  export CXXFLAGS="-O3 -felide-constructors -fno-exceptions -fno-rtti"
fi

timestamp="$(date +"%Y-%m-%dT%H:%M")"

