#!/usr/bin/env bash

modules defaults package

read_default version prefix package
read_default base_url prefix package

package_file="${package_name}-${package_version}-stable.${archive_format}"
package_dir="${package_name}-${package_version}-stable"

