#!/usr/bin/env bash

source "${extension_modules_path}/cli"

#  First do an install
modules "riak"
install

# Then do the upgrade parts
# TODO: Upgrade code
# move and symlink to preserve the old riak.conf / config files
# upgrade / move databases from old system.

