#!/usr/bin/env bash

modules core/package

package_definition \
  file "ImageMagick-${package_version}.${archive_format}" \
  dir "ImageMagick-${package_version}"

package_dependencies=( freetype libpng jpeg tiff libwmf lcms ghostscript)
