#!/usr/bin/env bash

modules package

package_definition \
  file "ImageMagick-${package_version}.${archive_format}" \
  dir "ImageMagick-${package_version}"

dependencies=( freetype libpng jpeg tiff libwmf lcms ghostscript)
