#!/usr/bin/env bash

description "Extension for managing vsftpd ()."

action "start" "Startup vsftpd."
action "stop" "Stop vsftpd."
action "restart" "Restart vsftpd."
action "status" "Display vsftpd status."
action "list" "List vsftpd master and worker processes."

show_help usage

