#!/usr/bin/env bash

npm_configure()
{
  move_directory "package" to "${package_dir}"
}

latest_version()
{
  json="$(curl http://registry.npmjs.org/npm/latest)"
  version="${json##*version\":\"}"
  version="${version%%\"*}"

  printf "%s" "${version}"
}
