#!/usr/bin/env bash

npm_extract()
{
  package_extract

  remove_paths "${package_dir}"
  if directory_exists "package"
  then
    move_directory "package" to "${package_dir}"
  fi
}

latest_version()
{
  json="$(curl http://registry.npmjs.org/npm/latest)"
  version="${json##*version\":\"}"
  version="${version%%\"*}"

  printf "%s" "${version}"
}
